version: '3'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
     MYSQL_DATABASE: mcca2
     MYSQL_USER: root
     MYSQL_PASSWORD: 
     MYSQL_ALLOW_EMPTY_PASSWORD: 1

volumes:
  dbdata:
